### PR TITLE
Issue #KN-686 feat: integration of pdf player as web component  in flutter app

### PR DESCRIPTION
**Pull request by santoshilimi**
Implementation Video: https://drive.google.com/file/d/1G0P1xvJg1iqxX8akXxiXG-tnEjtB9-QZ/view?usp=share_link

### CODE REVIEW

**Review by HarishGangula — CHANGES_REQUESTED** [review]
Add the player integration

**Review by HarishGangula — APPROVED** [review]

**Review by vinukumar-vs — COMMENTED** [review]
Can you check what is the size of the entire flutter_app folder.

I font want your repo clone is taking more time because of these samples.

**Comment by santoshilimi** [comment]
> Can you check what is the size of the entire flutter_app folder.
> 
> I font want your repo clone is taking more time because of these samples.
@vinukumar-vs 
Total size of flutter folder is 3.7 MB on disk

**Comment by santoshilimi** [comment]
Raised new PR

**Pull request closed without merging**
